import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { type Card, CardGroup } from "src/components/CardGroup";
import { Modal } from "src/components/Modal";
import { useRaspAtom } from "src/store/atoms";


const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [rasp, setRasp] = useRaspAtom()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pl-64 bg-neutral-100 h-screen w-screen">
        <div className="p-10">
          <CardGroup cards={rasp} />
          <Modal isOpen={isOpen} setIsOpen={setIsOpen} />
        </div>
      </main>
    </>
  );
};

export default Home;
