import { type NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import { fetchMessageData } from "src/services/messervice";


const Home: NextPage = () => {
  const [data, setData] = useState<any>([]);
  useEffect(() => {
    const fetchData = async () => {
      const d = await fetchMessageData();
      setData(d);
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pl-64 bg-neutral-100 h-screen w-screen">
        <div className="flex flex-col gap-2 pt-5">
          {data.map((d: any, i: number) =>
            <div
              key={i}
              className={`${(d.type == "Good") ? "bg-green-200" : (d.type === "Advert") ? "bg-orange-200" : "bg-red-200"}  p-4`}>
              {d.content} {d.raspberryId}
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
